[package]
name = "ambients"
version = "0.2.0"
edition = "2024"
license = "BlueOak-1.0.0"
readme = "README.md"
repository = "https://github.com/RossSmyth/ambients/"
description = "Easily systemd ambient capablities"
categories = [ "filesystem", "os::linux-apis", "api-bindings" ]
keywords = [ "systemd", "capabilities", "hardening" ]
exclude = [ "*.nix", "/npins" ]

[dependencies]
nix = { version = "0.31.3", features = ["time"], optional = true }
systemd = { version = "0.10.1", optional = true }

[features]
default = [ "checked_api", "fd_store" ]
checked_api = [ "dep:systemd"]
fd_store = [ "dep:systemd" ]
nightly = []
notify = [ "dep:nix" ]

[[example]]
name = "basic"
